# FPC & Lazarus is built on each platform (takes ~15mins) then stored in cache.
# Cache is removed if not used in 7 days and is restricted to 5gb. Each lazarus install is ~500mb.

name: autobuild

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env: 
      OS: ${{ matrix.config.os }}
      NAME: ${{ matrix.config.name }}
      LAZ_VER: ${{ matrix.config.LAZ_VER }}
      FPC_VER: ${{ matrix.config.FPC_VER }}
      LAZ_OPT: ${{ matrix.config.LAZ_OPT }}
      ARTIFACT: ${{ matrix.config.ARTIFACT }}
      FPCUP: ${{ matrix.config.FPCUP }}
      FPCUP_OPT: ${{ matrix.config.FPCUP_OPT }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: 'Windows 32'
            FPCUP: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.0b/fpclazup-i386-win32.exe'
            FPC_VER: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            LAZ_VER: 'trunk'
            LAZ_OPT: '--build-mode=WIN32'
            ARTIFACT: 'libsimpleocr32.dll'

          - os: windows-latest
            name: 'Windows 64'
            FPCUP: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.0b/fpclazup-x86_64-win64.exe'
            FPC_VER: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            LAZ_VER: 'trunk'
            LAZ_OPT: '--build-mode=WIN64'
            ARTIFACT: 'libsimpleocr64.dll'

          - os: ubuntu-latest
            name: 'Linux 64'
            FPCUP: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.0b/fpclazup-x86_64-linux'
            FPC_VER: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            LAZ_VER: 'trunk'
            LAZ_OPT: '--build-mode=LINUX64'
            ARTIFACT: 'libsimpleocr64.so'

          - os: macos-latest
            name: 'MacOS 64'
            FPCUP: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.0b/fpclazup-x86_64-darwin'
            FPCUP_OPT: '--lclplatform=cocoa'
            FPC_VER: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            LAZ_VER: 'trunk'
            LAZ_OPT: '--build-mode=DARWIN64'
            ARTIFACT: 'libsimpleocr64.dylib'

          - os: ubuntu-latest
            name: 'AArch64'
            FPCUP: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/1.8.0b/fpclazup-x86_64-linux'
            FPC_VER: 'https://svn.freepascal.org/svn/fpc/tags/release_3_2_0'
            LAZ_VER: 'trunk'
            LAZ_OPT: '--build-mode=AARCH64'
            ARTIFACT: 'libsimpleocr64.so.aarch64'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Generate Cache Hash
      run: echo ${{ env.FPCUP }}${{ env.FPC_VER }}${{ env.LAZ_VER }}${{ env.NAME }} > cache

    - name: Cache
      id: cache
      uses: actions/cache@v2.0.0
      with:
        path: lazarus/
        key: ${{ hashFiles('cache') }}

    - name: Install Dependencies
      if: env.OS == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install libgtk2.0-dev gcc-aarch64-linux-gnu
        sudo ln -s /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 /lib

    - name: Install Lazarus
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl --retry 5 -L -o fpcup ${{ env.FPCUP }}
        mkdir lazarus || true
        chmod +x fpcup
        ./fpcup --installdir=lazarus --fpcURL=${{ env.FPC_VER }} --lazURL=${{ env.LAZ_VER }} ${{ env.FPCUP_OPT }} --noconfirm --verbose

    - name: Install AArch64 Cross Compiler
      if: steps.cache.outputs.cache-hit != 'true' && env.NAME == 'AArch64'
      shell: bash
      run: |                          
        curl --retry 5 -L -o libs.zip https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.1/CrossLibsLinuxAarch64.zip && unzip libs.zip -d lazarus/
        curl --retry 5 -L -o bins.zip https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/linuxx64crossbins_v1.0/CrossBinsLinuxAarch64.zip && unzip bins.zip -d lazarus/cross/bin
        ./fpcup --installdir=lazarus --ostarget=linux --cputarget=aarch64 --only="FPCCleanOnly,FPCBuildOnly" --crossbindir=lazarus/cross/bin --crosslibdir=lazarus/cross/lib/aarch64-linux --noconfirm --verbose

    - name: Build SimpleOCR
      shell: bash
      run: |
        ./lazarus/lazarus/lazbuild ${{ env.LAZ_OPT }} "SimpleOCR.lpi"

    - name: Upload Artifact 
      uses: actions/upload-artifact@v2.0.1
      with:
        path: ${{ env.ARTIFACT }}

  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for builds to complete
      uses: Brandon-T/wait-for-check-action@v1
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_names: '["Windows 32", "Windows 64", "Linux 64", "MacOS 64", "AArch64"]'
        statuses: '["completed", "completed", "completed", "completed", "completed"]'
        conclusions: '["success", "success", "success", "success", "success"]'
        timeout: 1500
        poll_interval: 10

    - name: Download Artifacts
      if: github.event_name == 'push'
      uses: actions/download-artifact@v2

    - name: Update Release
      if: github.event_name == 'push'
      uses: Brandon-T/update-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        suffix_branch_name: true
        release_name: 'autobuild'
        file: 'artifact/*'
        is_file_glob: true
        release_notes: "Binaries for the most recent commit of this branch. Don't worry about the release date, it's wrong!"
        tag: 'autobuild'
        retry_count: 5
        bump_tag: true
        overwrite: true